### ISSUE TITLE
Apps in rc-app don't run any more

### ISSUE THREAD

**Issue by WolfgangFahl** [rc-dukes/dukes#23]
E.g.
```
Caused by: java.lang.UnsatisfiedLinkError: org.opencv.videoio.VideoCapture.VideoCapture_3()J
	at org.opencv.videoio.VideoCapture.VideoCapture_3(Native Method)
	at org.opencv.videoio.VideoCapture.<init>(VideoCapture.java:72)
	at nl.vaneijndhoven.opencv.video.LaneDetectionGUI.<init>(LaneDetectionGUI.java:43)
```

**Comment by WolfgangFahl** [comment]
see https://answers.opencv.org/question/39919/unsatisfiedlinkerror-in-java-with-videocapture/

`  NativeLibrary.load();
`
fixes this

**Comment by WolfgangFahl** [comment]
I am a bit confused about the layout  - there seem to be multiple versions of things. I'v started cleaning up but the LaneDetectionApp and StartLightDetectionApp still seems to be duplicate.

**Comment by WolfgangFahl** [comment]
add fontawesome with google material design icons to allow for similar layout as in webcontrol https://www.jensd.de/wordpress/?p=2094
