### ISSUE TITLE
TestAction fails on Travis even with very large timeout values

### ISSUE THREAD

**Issue by WolfgangFahl** [rc-dukes/dukes#45]
```
[INFO] Running nl.vaneijndhoven.dukes.action.TestAction
type=servoDirect
position=-100.0
type=servoDirect
position=-100.0
type=servoDirect
position=-60.0
type=servoDirect
position=-40.0
type=servoDirect
position=0.0
type=servoDirect
position=60.0
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.787 s <<< FAILURE! - in nl.vaneijndhoven.dukes.action.TestAction
[ERROR] testStraightLaneNavigator2(nl.vaneijndhoven.dukes.action.TestAction)  Time elapsed: 0.632 s  <<< FAILURE!
java.lang.AssertionError: timed out waiting for on next event
	at nl.vaneijndhoven.dukes.action.TestAction.check(TestAction.java:55)
	at nl.vaneijndhoven.dukes.action.TestAction.testStraightLaneNavigator2(TestAction.java:113)
```

**Comment by WolfgangFahl** [comment]
Tim would you have an idea why this is not reliably working?

**Comment by WolfgangFahl** [comment]
superfluous rxjava usage removal fixed this
