### ISSUE TITLE
java.lang.IllegalStateException: WebSocket is closed

### ISSUE THREAD

**Issue by WolfgangFahl** [rc-dukes/dukes#52]
java.lang.IllegalStateException: WebSocket is closed when trying to communicate with the dash2 simulator.

`at io.vertx.core.http.impl.WebSocketImplBase.checkClosed(WebSocketImplBase.java:342)
	at io.vertx.core.http.impl.ServerWebSocketImpl.close(ServerWebSocketImpl.java:124)
	at io.vertx.ext.web.handler.sockjs.impl.WebSocketTransport$WebSocketListener.lambda$sessionClosed$2(WebSocketTransport.java:150)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by WolfgangFahl** [comment]
reducing simulator image resolution from retina 2880x1800 to 1054x507 works around this issue

**Comment by WolfgangFahl** [comment]
will close for now.
